namespace scala com.gu.flexibleoctopus.model.thrift

/** date times are reprsented as i64 - epoch millis */
typedef i64 DateTime

/** 
* A single story bundle that maps directly to a piece of content in Composer 
*/
struct StoryBundle {

    1: required i64 id;

    2: required string composerId;

    3: required string pubCode;

    4: required string sectionCode;

    5: required Article article;

}

/**
* Represents a single article of a story bundle as generated by inCopy, 
* such as the headline, standfirst, or body text
*/
struct Article {

    // id for the article
    1: required i64 id;

    // id for the book section
    2: required i64 bookSectionId;

    // indicates whether the article is for web and/or print pulication
    3: required string forPublication;

    // current user that has the article checked out
    4: required string inUseBy; 

    // whether the article is currently checked out by a user
    5: required bool isCheckedOut;

    // when the last version of the article was saved
    6: required DateTime lastModified;

    // current legal status of the article
    7: required string lawyered;

    // the kind of text the article contains
    8: required string objectType;

    // the primary page that the article is on 
    9: required i64 onPage;

    // the issue date 
    10: required DateTime pubDate;

    // the workflow status of the article
    11: required string status;

}